complete -c deploy-local.sh -f
complete -c deploy-local.sh -s h -l help -d 'Show help'
complete -c deploy-local.sh -s u -l up -l ship -d 'Build from source, then force-deploy'
complete -c deploy-local.sh -s d -l deploy -l deploy-only -d 'Force redeploy / recreate (no build)'
complete -c deploy-local.sh -s b -l build -l build-only -d 'Build image only (skip deploy)'
complete -c deploy-local.sh -s r -l restart -d 'Restart containers (start if stopped)'
complete -c deploy-local.sh -s i -l info -l status -d 'Show containers, HTTP, and migration info'
complete -c deploy-local.sh -s k -l kill -l stop -l down -d 'Kill (stop) deployment containers'
complete -c deploy-local.sh -n '__fish_use_subcommand' -a up -d 'Build from source, then force-deploy'
complete -c deploy-local.sh -n '__fish_use_subcommand' -a deploy -d 'Force redeploy / recreate (no build)'
complete -c deploy-local.sh -n '__fish_use_subcommand' -a build -d 'Build image only (skip deploy)'
complete -c deploy-local.sh -n '__fish_use_subcommand' -a restart -d 'Restart containers (start if stopped)'
complete -c deploy-local.sh -n '__fish_use_subcommand' -a info -d 'Show containers, HTTP, and migration info'
complete -c deploy-local.sh -n '__fish_use_subcommand' -a kill -d 'Kill (stop) deployment containers'
complete -c deploy-local.sh -n '__fish_use_subcommand' -a status -d 'Alias for info'
complete -c deploy-local.sh -n '__fish_use_subcommand' -a stop -d 'Alias for kill'
complete -c deploy-local.sh -n '__fish_use_subcommand' -a help -d 'Show help'

complete -c deploy-local -f
complete -c deploy-local -s h -l help -d 'Show help'
complete -c deploy-local -s u -l up -l ship -d 'Build from source, then force-deploy'
complete -c deploy-local -s d -l deploy -l deploy-only -d 'Force redeploy / recreate (no build)'
complete -c deploy-local -s b -l build -l build-only -d 'Build image only (skip deploy)'
complete -c deploy-local -s r -l restart -d 'Restart containers (start if stopped)'
complete -c deploy-local -s i -l info -l status -d 'Show containers, HTTP, and migration info'
complete -c deploy-local -s k -l kill -l stop -l down -d 'Kill (stop) deployment containers'
complete -c deploy-local -n '__fish_use_subcommand' -a up -d 'Build from source, then force-deploy'
complete -c deploy-local -n '__fish_use_subcommand' -a deploy -d 'Force redeploy / recreate (no build)'
complete -c deploy-local -n '__fish_use_subcommand' -a build -d 'Build image only (skip deploy)'
complete -c deploy-local -n '__fish_use_subcommand' -a restart -d 'Restart containers (start if stopped)'
complete -c deploy-local -n '__fish_use_subcommand' -a info -d 'Show containers, HTTP, and migration info'
complete -c deploy-local -n '__fish_use_subcommand' -a kill -d 'Kill (stop) deployment containers'
complete -c deploy-local -n '__fish_use_subcommand' -a status -d 'Alias for info'
complete -c deploy-local -n '__fish_use_subcommand' -a stop -d 'Alias for kill'
complete -c deploy-local -n '__fish_use_subcommand' -a help -d 'Show help'
