complete -c moz -s h -l help -d 'Show help'
complete -c moz -s u -l up -l ship -d 'Build from source, then deploy'
complete -c moz -s d -l deploy-only -d 'Redeploy existing image (default)'
complete -c moz -s b -l build-only -d 'Build image only (skip deploy)'
complete -c moz -s s -l stop -l down -d 'Stop deployment containers'
