# Disable path completions so only moz options/subcommands appear.
complete -c moz -f
complete -c moz -s h -l help -d 'Show help'
complete -c moz -s u -l up -l ship -d 'Build from source, then force-deploy'
complete -c moz -s d -l deploy -l deploy-only -d 'Force redeploy / recreate (no build)'
complete -c moz -s b -l build -l build-only -d 'Build image only (skip deploy)'
complete -c moz -s r -l restart -d 'Restart containers (start if stopped)'
complete -c moz -s i -l info -l status -d 'Show containers, HTTP, and migration info'
complete -c moz -s k -l kill -l stop -l down -d 'Kill (stop) deployment containers'
complete -c moz -n '__fish_use_subcommand' -a up -d 'Build from source, then force-deploy'
complete -c moz -n '__fish_use_subcommand' -a deploy -d 'Force redeploy / recreate (no build)'
complete -c moz -n '__fish_use_subcommand' -a build -d 'Build image only (skip deploy)'
complete -c moz -n '__fish_use_subcommand' -a restart -d 'Restart containers (start if stopped)'
complete -c moz -n '__fish_use_subcommand' -a info -d 'Show containers, HTTP, and migration info'
complete -c moz -n '__fish_use_subcommand' -a kill -d 'Kill (stop) deployment containers'
complete -c moz -n '__fish_use_subcommand' -a status -d 'Alias for info'
complete -c moz -n '__fish_use_subcommand' -a stop -d 'Alias for kill'
complete -c moz -n '__fish_use_subcommand' -a help -d 'Show help'
