name: lobe-chat-development
services:
  network-service:
    image: alpine
    container_name: lobe-network
    restart: always
    ports:
      - '${RUSTFS_PORT}:9000' # RustFS API
      - '9001:9001' # RustFS Console
    command: tail -f /dev/null
    networks:
      - lobe-network

  postgresql:
    extends:
      file: docker-compose/dev/docker-compose.yml
      service: postgresql
  redis:
    extends:
      file: docker-compose/dev/docker-compose.yml
      service: redis
  rustfs:
    extends:
      file: docker-compose/dev/docker-compose.yml
      service: rustfs
  rustfs-init:
    extends:
      file: docker-compose/dev/docker-compose.yml
      service: rustfs-init
  searxng:
    extends:
      file: docker-compose/dev/docker-compose.yml
      service: searxng

volumes:
  data:
    driver: local
  redis_data:
    driver: local
  rustfs-data:
    driver: local

networks:
  lobe-network:
    driver: bridge
