import type { PartialDeep } from 'type-fest';
import { z } from 'zod';

import type { LobeToolRenderType } from '../../tool';

// ToolIntervention must be defined first to avoid circular dependency
export interface ToolIntervention {
  rejectedReason?: string;
  status?: 'pending' | 'approved' | 'rejected' | 'aborted' | 'none';
}

export const ToolInterventionSchema = z.object({
  rejectedReason: z.string().optional(),
  status: z.enum(['pending', 'approved', 'rejected', 'aborted', 'none']).optional(),
});

export interface ChatPluginPayload {
  apiName: string;
  arguments: string;
  identifier: string;
  intervention?: ToolIntervention;
  type: LobeToolRenderType;
}

/**
 * Tool source indicates where the tool comes from
 */
export type ToolSource = 'builtin' | 'client' | 'mcp' | 'klavis' | 'lobehubSkill';

/**
 * Tool executor indicates where the tool is executed for a given invocation.
 * Orthogonal to ToolSource (origin): executor describes dispatch target.
 */
export type ToolExecutor = 'client' | 'server';

/**
 * Normalized "this tool spawns a subagent" descriptor. Adapters set this on
 * the main-agent tool_use that triggers a sub-conversation (e.g. Claude
 * Code's `Task` tool, Codex's subtask equivalent) so downstream consumers
 * can allocate a Thread / route the subagent's inner tool_uses without
 * needing to special-case per-adapter tool identifiers or re-parse
 * `arguments`. Paired with `parentToolCallId` on the inner tool_uses.
 */
export interface SubagentSpawnInfo {
  /** Free-form description of the delegated task, sourced from the tool input. */
  description?: string;
  /**
   * Adapter-specific subagent template label (CC's `subagent_type`,
   * Codex's equivalent, ...). Used purely for UI / metadata.
   */
  subagentType?: string;
}

export interface ChatToolPayload {
  apiName: string;
  arguments: string;
  /**
   * Tool executor: dispatch target for this invocation.
   */
  executor?: ToolExecutor;
  id: string;
  identifier: string;
  intervention?: ToolIntervention;
  /**
   * When this tool_use was spawned BY a subagent (e.g. a tool call
   * happening inside a CC `Task` subagent), this carries the id of the
   * outer tool_use that spawned the subagent. Lets the renderer
   * reconstruct parent-child tool relationships without joining Threads
   * on every read, and lets adapters that don't route subagent tools
   * into a separate Thread still carry the lineage.
   *
   * Absent for top-level (main-agent) tool calls.
   */
  parentToolCallId?: string;
  result_msg_id?: string;
  /**
   * Tool source indicates where the tool comes from
   */
  source?: ToolSource;
  /**
   * Present on a tool_use that spawns a subagent. Adapter-agnostic
   * marker paired with `parentToolCallId` on the subagent's inner tools.
   * The executor creates a subagent Thread when it sees this, but any
   * renderer can also key off it directly (no Thread lookup needed
   * to show "this tool_use is a subagent spawn").
   */
  subagentSpawn?: SubagentSpawnInfo;
  thoughtSignature?: string;
  type: LobeToolRenderType;
}

/**
 * Tool execution result from tool messages
 */
export interface ChatToolResult {
  content: string | null;
  error?: any;
  id: string;
  state?: any;
}

/**
 * Chat tool payload with merged execution result
 */
export interface ChatToolPayloadWithResult extends ChatToolPayload {
  intervention?: ToolIntervention;
  result?: ChatToolResult;
  result_msg_id?: string;
}

export interface ToolsCallingContext {
  topicId?: string;
}
/**
 * The function that the model called.
 */
export interface ToolFunction {
  /**
   * The arguments to call the function with, as generated by the model in JSON
   * format. Note that the model does not always generate valid JSON, and may
   * hallucinate parameters not defined by your function schema. Validate the
   * arguments in your code before calling your function.
   */
  arguments: string;

  /**
   * The name of the function to call.
   */
  name: string;
}

export interface MessageToolCall {
  /**
   * The function that the model called.
   */
  function: ToolFunction;

  /**
   * The ID of the tool call.
   */
  id: string;

  thoughtSignature?: string;
  /**
   * The type of the tool. Currently, only `function` is supported.
   */
  type: 'function' | string;
}

export type MessageToolCallChunk = PartialDeep<MessageToolCall> & { index: number };

export const MessageToolCallSchema = z.object({
  function: z.object({
    arguments: z.string(),
    name: z.string(),
  }),
  id: z.string(),
  type: z.string(),
});

export const SubagentSpawnInfoSchema = z.object({
  description: z.string().optional(),
  subagentType: z.string().optional(),
});

export const ChatToolPayloadSchema = z.object({
  apiName: z.string(),
  arguments: z.string(),
  id: z.string(),
  identifier: z.string(),
  intervention: ToolInterventionSchema.optional(),
  parentToolCallId: z.string().optional(),
  result_msg_id: z.string().optional(),
  subagentSpawn: SubagentSpawnInfoSchema.optional(),
  thoughtSignature: z.string().optional(),
  type: z.string(),
});

/**
 * Chat message error object
 */
export interface ChatMessagePluginError {
  body?: any;
  message: string;
  type: string;
}
