import type { ChatModelCard } from '@lobechat/types';
import { omit } from 'es-toolkit/compat';
import type { AiModelType } from 'model-bank';
import { CHAT_MODEL_IMAGE_GENERATION_PARAMS, IMAGE_GENERATION_MODEL_WHITELIST } from 'model-bank';

export { IMAGE_GENERATION_MODEL_WHITELIST, isAutoGeneratedImageModelId } from 'model-bank';

const IMAGE_MODEL_SUFFIX = ':image';

/**
 * Whether this chat card should get a sibling `{id}:image` entry for the
 * provider Image tab.
 *
 * Prefer modality/ability signals (`imageOutput`). Keep the Gemini whitelist
 * as a fallback for providers that never set that flag. Skip OpenRouter
 * routers — they are not dedicated generators.
 */
export const shouldSynthesizeImageModel = (model: ChatModelCard): boolean => {
  if (model.id.endsWith(IMAGE_MODEL_SUFFIX)) return false;
  if (model.type === 'image') return false;
  if (model.id === 'openrouter/auto' || model.id.startsWith('openrouter/auto-')) return false;

  if (model.imageOutput) return true;

  return IMAGE_GENERATION_MODEL_WHITELIST.some((pattern) => model.id.endsWith(pattern));
};

/**
 * Process model list: ensure type field exists and synthesize image-generation
 * siblings for modality-capable (or whitelisted) chat models.
 */
export async function postProcessModelList(
  models: ChatModelCard[],
  getModelTypeProperty?: (modelId: string) => Promise<AiModelType>,
): Promise<ChatModelCard[]> {
  // 1. Ensure all models have type field
  const finalModels = await Promise.all(
    models.map(async (model) => {
      let modelType: AiModelType | undefined = model.type;

      if (!modelType && getModelTypeProperty) {
        modelType = await getModelTypeProperty(model.id);
      }

      return {
        ...model,
        type: modelType || 'chat',
      };
    }),
  );

  // 2. Synthesize Image-tab clones (idempotent if factory re-runs this)
  const imageModels: ChatModelCard[] = [];
  const existingIds = new Set(finalModels.map((model) => model.id));

  for (const model of finalModels) {
    if (!shouldSynthesizeImageModel(model)) continue;

    const imageModelId = `${model.id}${IMAGE_MODEL_SUFFIX}`;
    if (existingIds.has(imageModelId)) continue;
    existingIds.add(imageModelId);

    const rest = omit(model, [
      'files',
      'functionCall',
      'reasoning',
      'search',
      'imageOutput',
      'video',
      'vision',
      'type',
      'parameters',
    ]);

    imageModels.push({
      ...rest,
      id: imageModelId,
      parameters: CHAT_MODEL_IMAGE_GENERATION_PARAMS,
      type: 'image',
    });
  }

  return [...finalModels, ...imageModels];
}
