import type { AIChatModelCard } from '../types/aiModel';

const atlascloudChatModels: AIChatModelCard[] = [
  // DeepSeek
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 131_072,
    description: 'DeepSeek V4 Pro — reasoning model with hybrid thinking mode.',
    displayName: 'DeepSeek V4 Pro',
    enabled: true,
    id: 'deepseek-ai/deepseek-v4-pro',
    maxOutput: 32_768,
    type: 'chat',
  },
  {
    abilities: { functionCall: true },
    contextWindowTokens: 131_072,
    description: 'DeepSeek V4 Flash — fast, cost-effective reasoning model.',
    displayName: 'DeepSeek V4 Flash',
    enabled: true,
    id: 'deepseek-ai/deepseek-v4-flash',
    maxOutput: 32_768,
    type: 'chat',
  },
  {
    abilities: { reasoning: true },
    contextWindowTokens: 131_072,
    displayName: 'DeepSeek R1 0528',
    enabled: true,
    id: 'deepseek-ai/deepseek-r1-0528',
    maxOutput: 32_768,
    type: 'chat',
  },
  {
    abilities: { functionCall: true },
    contextWindowTokens: 131_072,
    displayName: 'DeepSeek V3.2',
    enabled: true,
    id: 'deepseek-ai/deepseek-v3.2',
    type: 'chat',
  },
  {
    abilities: { functionCall: true },
    contextWindowTokens: 131_072,
    displayName: 'DeepSeek V3.1',
    enabled: true,
    id: 'deepseek-ai/DeepSeek-V3.1',
    type: 'chat',
  },
  {
    abilities: {},
    contextWindowTokens: 131_072,
    displayName: 'DeepSeek V3-0324',
    id: 'deepseek-ai/DeepSeek-V3-0324',
    type: 'chat',
  },
  {
    abilities: {},
    contextWindowTokens: 131_072,
    displayName: 'DeepSeek V3.1 Terminus',
    id: 'deepseek-ai/DeepSeek-V3.1-Terminus',
    type: 'chat',
  },
  {
    abilities: {},
    contextWindowTokens: 131_072,
    displayName: 'DeepSeek V3.2 Exp',
    id: 'deepseek-ai/DeepSeek-V3.2-Exp',
    type: 'chat',
  },
  {
    abilities: { vision: true },
    contextWindowTokens: 131_072,
    displayName: 'DeepSeek OCR',
    id: 'deepseek-ai/deepseek-ocr',
    type: 'chat',
  },
  // Anthropic (Claude)
  {
    abilities: { functionCall: true, vision: true },
    contextWindowTokens: 200_000,
    displayName: 'Claude Sonnet 4.6',
    enabled: true,
    id: 'anthropic/claude-sonnet-4.6',
    maxOutput: 64_000,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, vision: true },
    contextWindowTokens: 1_000_000,
    displayName: 'Claude Opus 4.8',
    enabled: true,
    id: 'anthropic/claude-opus-4.8',
    maxOutput: 128_000,
    type: 'chat',
  },
  {
    abilities: { functionCall: true },
    contextWindowTokens: 200_000,
    displayName: 'Claude Haiku 4.5',
    enabled: true,
    id: 'anthropic/claude-haiku-4.5-20251001',
    maxOutput: 64_000,
    type: 'chat',
  },
  // OpenAI
  {
    abilities: { functionCall: true, vision: true },
    contextWindowTokens: 128_000,
    displayName: 'GPT-5.5',
    enabled: true,
    id: 'openai/gpt-5.5',
    maxOutput: 128_000,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, vision: true },
    contextWindowTokens: 128_000,
    displayName: 'GPT-5.4',
    id: 'openai/gpt-5.4',
    maxOutput: 128_000,
    type: 'chat',
  },
  // Google
  {
    abilities: { functionCall: true, vision: true },
    contextWindowTokens: 1_000_000,
    displayName: 'Gemini 3.5 Flash',
    enabled: true,
    id: 'google/gemini-3.5-flash',
    maxOutput: 8_192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, vision: true },
    contextWindowTokens: 1_000_000,
    displayName: 'Gemini 3.1 Pro Preview',
    id: 'google/gemini-3.1-pro-preview',
    maxOutput: 8_192,
    type: 'chat',
  },
  {
    abilities: {},
    contextWindowTokens: 1_000_000,
    displayName: 'Gemini 3.1 Flash Lite',
    id: 'google/gemini-3.1-flash-lite',
    maxOutput: 8_192,
    type: 'chat',
  },
  // Qwen
  {
    abilities: { functionCall: true },
    contextWindowTokens: 131_072,
    displayName: 'Qwen3-235B-A22B Instruct 2507',
    enabled: true,
    id: 'Qwen/Qwen3-235B-A22B-Instruct-2507',
    type: 'chat',
  },
  {
    abilities: { reasoning: true },
    contextWindowTokens: 131_072,
    displayName: 'Qwen3-235B-A22B Thinking 2507',
    id: 'qwen/qwen3-235b-a22b-thinking-2507',
    type: 'chat',
  },
  {
    abilities: { functionCall: true },
    contextWindowTokens: 131_072,
    displayName: 'Qwen3-Next-80B-A3B Instruct',
    enabled: true,
    id: 'Qwen/Qwen3-Next-80B-A3B-Instruct',
    type: 'chat',
  },
  {
    abilities: { reasoning: true },
    contextWindowTokens: 131_072,
    displayName: 'Qwen3-Next-80B-A3B Thinking',
    id: 'Qwen/Qwen3-Next-80B-A3B-Thinking',
    type: 'chat',
  },
  {
    abilities: { functionCall: true },
    contextWindowTokens: 131_072,
    displayName: 'Qwen3-30B-A3B Instruct 2507',
    id: 'Qwen/Qwen3-30B-A3B-Instruct-2507',
    type: 'chat',
  },
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'Qwen3-30B-A3B', id: 'qwen/qwen3-30b-a3b', type: 'chat' },
  { abilities: { reasoning: true }, contextWindowTokens: 131_072, displayName: 'Qwen3-30B-A3B Thinking', id: 'qwen/qwen3-30b-a3b-thinking-2507', type: 'chat' },
  { abilities: { functionCall: true }, contextWindowTokens: 131_072, displayName: 'Qwen3-32B', id: 'qwen/qwen3-32b', type: 'chat' },
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'Qwen3-8B', id: 'qwen/qwen3-8b', type: 'chat' },
  { abilities: { functionCall: true }, contextWindowTokens: 131_072, displayName: 'Qwen3 Coder', id: 'Qwen/Qwen3-Coder', type: 'chat' },
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'Qwen3 Coder Next', id: 'qwen/qwen3-coder-next', type: 'chat' },
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'Qwen3 Max 2026-01-23', id: 'qwen/qwen3-max-2026-01-23', type: 'chat' },
  { abilities: { vision: true }, contextWindowTokens: 131_072, displayName: 'Qwen3-VL-235B-A22B Instruct', id: 'Qwen/Qwen3-VL-235B-A22B-Instruct', type: 'chat' },
  { abilities: { vision: true, reasoning: true }, contextWindowTokens: 131_072, displayName: 'Qwen3-VL-235B Thinking', id: 'qwen/qwen3-vl-235b-a22b-thinking', type: 'chat' },
  { abilities: { vision: true }, contextWindowTokens: 131_072, displayName: 'Qwen3-VL-30B Instruct', id: 'qwen/qwen3-vl-30b-a3b-instruct', type: 'chat' },
  { abilities: { vision: true, reasoning: true }, contextWindowTokens: 131_072, displayName: 'Qwen3-VL-30B Thinking', id: 'qwen/qwen3-vl-30b-a3b-thinking', type: 'chat' },
  { abilities: { vision: true }, contextWindowTokens: 131_072, displayName: 'Qwen3-VL-8B Instruct', id: 'qwen/qwen3-vl-8b-instruct', type: 'chat' },
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'Qwen3.5-397B-A17B', id: 'qwen/qwen3.5-397b-a17b', type: 'chat' },
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'Qwen3.5-122B-A10B', id: 'qwen/qwen3.5-122b-a10b', type: 'chat' },
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'Qwen3.5-35B-A3B', id: 'qwen/qwen3.5-35b-a3b', type: 'chat' },
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'Qwen3.5-27B', id: 'qwen/qwen3.5-27b', type: 'chat' },
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'Qwen3.6-35B-A3B', id: 'qwen/qwen3.6-35b-a3b', type: 'chat' },
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'Qwen3.6 Plus', id: 'qwen/qwen3.6-plus', type: 'chat' },
  { abilities: {}, contextWindowTokens: 32_768, displayName: 'Qwen2.5-7B Instruct', id: 'qwen/qwen2.5-7b-instruct', type: 'chat' },
  // Moonshot (Kimi)
  {
    abilities: { functionCall: true },
    contextWindowTokens: 131_072,
    displayName: 'Kimi K2 Instruct',
    enabled: true,
    id: 'moonshotai/Kimi-K2-Instruct',
    type: 'chat',
  },
  { abilities: { reasoning: true }, contextWindowTokens: 131_072, displayName: 'Kimi K2 Thinking', id: 'moonshotai/Kimi-K2-Thinking', type: 'chat' },
  { abilities: { functionCall: true }, contextWindowTokens: 131_072, displayName: 'Kimi K2 Instruct 0905', id: 'moonshotai/Kimi-K2-Instruct-0905', type: 'chat' },
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'Kimi K2.5', id: 'moonshotai/kimi-k2.5', type: 'chat' },
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'Kimi K2.6', id: 'moonshotai/kimi-k2.6', type: 'chat' },
  // Zhipu (GLM)
  { abilities: { functionCall: true }, contextWindowTokens: 131_072, displayName: 'GLM-5', enabled: true, id: 'zai-org/glm-5', type: 'chat' },
  { abilities: { functionCall: true }, contextWindowTokens: 131_072, displayName: 'GLM-5 Turbo', id: 'zai-org/glm-5-turbo', type: 'chat' },
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'GLM-5.1', id: 'zai-org/glm-5.1', type: 'chat' },
  { abilities: { vision: true }, contextWindowTokens: 131_072, displayName: 'GLM-5V Turbo', id: 'zai-org/glm-5v-turbo', type: 'chat' },
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'GLM-4.7', id: 'zai-org/glm-4.7', type: 'chat' },
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'GLM-4.6', id: 'zai-org/GLM-4.6', type: 'chat' },
  // MiniMax
  { abilities: { functionCall: true }, contextWindowTokens: 204_800, displayName: 'MiniMax-M2', enabled: true, id: 'MiniMaxAI/MiniMax-M2', type: 'chat' },
  { abilities: {}, contextWindowTokens: 204_800, displayName: 'MiniMax-M2.1', id: 'minimaxai/minimax-m2.1', type: 'chat' },
  { abilities: {}, contextWindowTokens: 204_800, displayName: 'MiniMax-M2.5', id: 'minimaxai/minimax-m2.5', type: 'chat' },
  { abilities: {}, contextWindowTokens: 204_800, displayName: 'MiniMax-M2.7', id: 'minimaxai/minimax-m2.7', type: 'chat' },
  // xAI
  { abilities: { functionCall: true, vision: true }, contextWindowTokens: 131_072, displayName: 'Grok 4.3', id: 'xai/grok-4.3', type: 'chat' },
  // Kwaipilot
  { abilities: { functionCall: true }, contextWindowTokens: 131_072, displayName: 'KAT Coder Pro V2', id: 'kwaipilot/kat-coder-pro-v2', type: 'chat' },
  // Other
  { abilities: {}, contextWindowTokens: 131_072, displayName: 'Owl', id: 'owl', type: 'chat' },
];

export default atlascloudChatModels;
