import { type AIChatModelCard } from '../types/aiModel';

// ref: https://help.aliyun.com/zh/model-studio/coding-plan-overview
// Official Bailian Coding Plan model list (exact versions only).
// Metadata enriched from models.dev → alibaba-coding-plan-cn

const bailianCodingPlanChatModels: AIChatModelCard[] = [
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 1_000_000,
    description: 'Multimodal Qwen workhorse for long-context agents, visual inputs, and coding',
    displayName: 'Qwen3.7 Plus',
    enabled: true,
    family: 'qwen',
    generation: 'qwen3.7',
    id: 'qwen3.7-plus',
    maxOutput: 64_000,
    organization: 'Qwen',
    releasedAt: '2026-06-02',
    settings: {
      // reasoning_options: [{"type": "toggle"}]
      extendParams: ['enableReasoning'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
      video: true,
    },
    contextWindowTokens: 1_000_000,
    description: 'Qwen vision-language model for visual reasoning, documents, and agent tasks',
    displayName: 'Qwen3.6 Plus',
    enabled: true,
    family: 'qwen',
    generation: 'qwen3.6',
    id: 'qwen3.6-plus',
    maxOutput: 65_536,
    organization: 'Qwen',
    releasedAt: '2026-04-02',
    settings: {
      // reasoning_options: [{"type": "toggle"}]
      extendParams: ['enableReasoning'],
    },
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 262_144,
    description: 'Kimi multimodal agent model for visual understanding, coding, and planning',
    displayName: 'Kimi K2.5',
    enabled: true,
    family: 'kimi',
    generation: 'kimi-k2.5',
    id: 'kimi-k2.5',
    maxOutput: 32_768,
    organization: 'Moonshot',
    releasedAt: '2026-01-27',
    settings: {
      // reasoning_options: [{"type": "toggle"}]
      extendParams: ['enableReasoning'],
    },
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 202_752,
    description: 'Flagship GLM model for hybrid reasoning, coding, and agentic engineering',
    displayName: 'GLM-5',
    enabled: true,
    family: 'glm',
    generation: 'glm-5',
    id: 'glm-5',
    maxOutput: 16_384,
    organization: 'Zhipu',
    releasedAt: '2026-02-11',
    settings: {
      // reasoning_options: [{"type": "toggle"}]
      extendParams: ['enableReasoning'],
    },
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 196_608,
    description: 'MiniMax model for chat, coding, office work, and agentic tasks',
    displayName: 'MiniMax-M2.5',
    enabled: true,
    family: 'minimax',
    generation: 'minimax-m2.5',
    id: 'MiniMax-M2.5',
    maxOutput: 24_576,
    organization: 'MiniMax',
    releasedAt: '2026-02-12',
    // reasoning_options: []
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 1_000_000,
    description: 'Qwen vision-language model for visual reasoning, documents, and agent tasks',
    displayName: 'Qwen3.5 Plus',
    enabled: false,
    family: 'qwen',
    generation: 'qwen3.5',
    id: 'qwen3.5-plus',
    maxOutput: 65_536,
    organization: 'Qwen',
    releasedAt: '2026-02-16',
    settings: {
      // reasoning_options: [{"type": "toggle"}]
      extendParams: ['enableReasoning'],
    },
    type: 'chat',
  },
  {
    abilities: { functionCall: true },
    contextWindowTokens: 262_144,
    description: 'Flagship Qwen model for complex reasoning, coding, and agentic workflows',
    displayName: 'Qwen3 Max',
    enabled: false,
    family: 'qwen',
    generation: 'qwen3',
    id: 'qwen3-max-2026-01-23',
    maxOutput: 32_768,
    organization: 'Qwen',
    releasedAt: '2026-01-23',
    type: 'chat',
  },
  {
    abilities: { functionCall: true, structuredOutput: true },
    contextWindowTokens: 262_144,
    description: 'Qwen coding model for software agents, repository edits, and code reasoning',
    displayName: 'Qwen3 Coder Next',
    enabled: false,
    family: 'qwen',
    generation: 'qwen3',
    id: 'qwen3-coder-next',
    maxOutput: 65_536,
    organization: 'Qwen',
    releasedAt: '2026-02-03',
    type: 'chat',
  },
  {
    abilities: { functionCall: true },
    contextWindowTokens: 1_000_000,
    description: 'Qwen coding model for software agents, repository edits, and code reasoning',
    displayName: 'Qwen3 Coder Plus',
    enabled: false,
    family: 'qwen',
    generation: 'qwen3',
    id: 'qwen3-coder-plus',
    maxOutput: 65_536,
    organization: 'Qwen',
    releasedAt: '2025-07-23',
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 202_752,
    description: 'Flagship GLM model for hybrid reasoning, coding, and agentic engineering',
    displayName: 'GLM-4.7',
    enabled: false,
    family: 'glm',
    generation: 'glm-4.7',
    id: 'glm-4.7',
    maxOutput: 16_384,
    organization: 'Zhipu',
    releasedAt: '2025-12-22',
    settings: {
      // reasoning_options: [{"type": "toggle"}]
      extendParams: ['enableReasoning'],
    },
    type: 'chat',
  },
];

export default bailianCodingPlanChatModels;
