import type { AIChatModelCard } from '../types/aiModel';

// https://melious.ai/hub/models
// Catalog and capabilities: GET https://api.melious.ai/v1/models?include_meta=true

const meliousChatModels: AIChatModelCard[] = [
  {
    contextWindowTokens: 65_536,
    displayName: 'Apertus 70B',
    id: 'apertus-70b',
    organization: 'Swiss AI Initiative',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
    },
    contextWindowTokens: 164_000,
    displayName: 'DeepSeek R1 0528',
    family: 'deepseek',
    generation: 'deepseek-r1',
    id: 'deepseek-r1-0528',
    organization: 'DeepSeek',
    releasedAt: '2025-05-28',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
    },
    contextWindowTokens: 164_000,
    displayName: 'DeepSeek V3.2',
    family: 'deepseek',
    generation: 'deepseek-v3.2',
    id: 'deepseek-v3.2',
    organization: 'DeepSeek',
    releasedAt: '2025-12-01',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
    },
    contextWindowTokens: 1_000_000,
    displayName: 'DeepSeek V4 Flash 0731',
    family: 'deepseek',
    generation: 'deepseek-v4',
    id: 'deepseek-v4-flash-0731',
    organization: 'DeepSeek',
    releasedAt: '2026-07-31',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    displayName: 'DeepSeek V4.1 Flash',
    enabled: true,
    family: 'deepseek',
    generation: 'deepseek-v4.1',
    id: 'deepseek-v4.1-flash',
    organization: 'DeepSeek',
    releasedAt: '2026-09-10',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      structuredOutput: true,
    },
    contextWindowTokens: 200_000,
    displayName: 'Devstral 2 123B Instruct',
    family: 'devstral',
    id: 'devstral-2-123b-instruct-2512',
    maxOutput: 8_192,
    organization: 'Mistral',
    releasedAt: '2025-12-09',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 40_000,
    displayName: 'Gemma 3 27B IT',
    family: 'gemma',
    generation: 'gemma-3',
    id: 'gemma-3-27b-it',
    knowledgeCutoff: '2024-08',
    organization: 'Google',
    releasedAt: '2025-03-12',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      video: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    displayName: 'Gemma 4 26B A4B',
    family: 'gemma',
    generation: 'gemma-4',
    id: 'gemma-4-26b-a4b',
    organization: 'Google',
    releasedAt: '2026-04-02',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      video: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    displayName: 'Gemma 4 31B',
    family: 'gemma',
    generation: 'gemma-4',
    id: 'gemma-4-31b',
    organization: 'Google',
    releasedAt: '2026-04-02',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
    },
    contextWindowTokens: 203_000,
    displayName: 'GLM-5',
    family: 'glm',
    generation: 'glm-5',
    id: 'glm-5',
    organization: 'Zhipu',
    releasedAt: '2026-02-11',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
    },
    contextWindowTokens: 203_000,
    displayName: 'GLM 5.1',
    family: 'glm',
    generation: 'glm-5.1',
    id: 'glm-5.1',
    organization: 'Zhipu',
    releasedAt: '2026-04-07',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
    },
    contextWindowTokens: 1_000_000,
    displayName: 'GLM 5.3',
    enabled: true,
    family: 'glm',
    generation: 'glm-5.3',
    id: 'glm-5.3',
    organization: 'Zhipu',
    releasedAt: '2026-08-25',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      video: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    displayName: 'GLM 5.3 Flash',
    family: 'glm',
    generation: 'glm-5.3',
    id: 'glm-5.3-flash',
    organization: 'Zhipu',
    releasedAt: '2026-08-25',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
    },
    contextWindowTokens: 131_072,
    displayName: 'GPT-OSS 120B',
    enabled: true,
    family: 'gpt-oss',
    generation: 'gpt-oss',
    id: 'gpt-oss-120b',
    knowledgeCutoff: '2024-06',
    organization: 'OpenAI',
    releasedAt: '2025-08-05',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
    },
    contextWindowTokens: 131_000,
    displayName: 'GPT-OSS 20B',
    family: 'gpt-oss',
    generation: 'gpt-oss',
    id: 'gpt-oss-20b',
    knowledgeCutoff: '2024-06',
    organization: 'OpenAI',
    releasedAt: '2025-08-05',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 128_000,
    displayName: 'Hermes 4 405B',
    family: 'hermes',
    id: 'hermes-4-405b',
    organization: 'NousResearch',
    releasedAt: '2025-08-26',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 131_072,
    displayName: 'Holo2 30B A3B',
    id: 'holo2-30b-a3b',
    organization: 'H Company',
    releasedAt: '2025-11-10',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 262_000,
    displayName: 'Kimi K2.5',
    family: 'kimi',
    generation: 'kimi-k2.5',
    id: 'kimi-k2.5',
    organization: 'Moonshot',
    releasedAt: '2026-01-27',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      video: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    displayName: 'Kimi K2.6',
    family: 'kimi',
    generation: 'kimi-k2.6',
    id: 'kimi-k2.6',
    organization: 'Moonshot',
    releasedAt: '2026-04-21',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      video: true,
      vision: true,
    },
    contextWindowTokens: 262_144,
    displayName: 'Kimi K2.7 Code',
    family: 'kimi',
    generation: 'kimi-k2.7',
    id: 'kimi-k2.7-code',
    organization: 'Moonshot',
    releasedAt: '2026-06-12',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      video: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    displayName: 'Kimi K3',
    family: 'kimi',
    generation: 'kimi-k3',
    id: 'kimi-k3',
    organization: 'Moonshot',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      structuredOutput: true,
    },
    contextWindowTokens: 128_000,
    displayName: 'Llama 3.1 405B Instruct',
    family: 'llama',
    generation: 'llama-3.1',
    id: 'llama-3.1-405b-instruct',
    knowledgeCutoff: '2023-12',
    organization: 'Meta',
    releasedAt: '2024-07-23',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
    },
    contextWindowTokens: 128_000,
    displayName: 'Llama 3.1 8B Instruct',
    family: 'llama',
    generation: 'llama-3.1',
    id: 'llama-3.1-8b-instruct',
    knowledgeCutoff: '2023-12',
    organization: 'Meta',
    releasedAt: '2024-07-23',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      structuredOutput: true,
    },
    contextWindowTokens: 131_072,
    displayName: 'Llama 3.3 70B Instruct',
    family: 'llama',
    generation: 'llama-3.3',
    id: 'llama-3.3-70b-instruct',
    knowledgeCutoff: '2023-12',
    organization: 'Meta',
    releasedAt: '2024-12-06',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
    },
    contextWindowTokens: 197_000,
    displayName: 'MiniMax M2.5',
    family: 'minimax',
    generation: 'minimax-m2.5',
    id: 'minimax-m2.5',
    organization: 'MiniMax',
    releasedAt: '2026-02-12',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
    },
    contextWindowTokens: 192_000,
    displayName: 'MiniMax M2.7',
    family: 'minimax',
    generation: 'minimax-m2.7',
    id: 'minimax-m2.7',
    organization: 'MiniMax',
    releasedAt: '2026-03-18',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      video: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    displayName: 'MiniMax M3',
    enabled: true,
    family: 'minimax',
    generation: 'minimax-m3',
    id: 'minimax-m3',
    organization: 'MiniMax',
    releasedAt: '2026-06-02',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 131_072,
    displayName: 'Mistral Small 3.2 24B Instruct',
    family: 'mistral',
    id: 'mistral-small-3.2-24b-instruct',
    organization: 'Mistral',
    releasedAt: '2025-06-20',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 262_144,
    displayName: 'Mistral Small 4 119B Instruct',
    family: 'mistral',
    id: 'mistral-small-4-119b-instruct',
    organization: 'Mistral',
    releasedAt: '2026-03-16',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
    },
    contextWindowTokens: 128_000,
    displayName: 'Nemotron 3 Nano 30B A3B',
    id: 'nemotron-3-nano-30b-a3b',
    maxOutput: 8_192,
    organization: 'Nvidia',
    releasedAt: '2025-12-15',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 128_000,
    displayName: 'Pixtral 12B 2409',
    family: 'pixtral',
    id: 'pixtral-12b-2409',
    organization: 'Mistral',
    releasedAt: '2024-09-11',
    type: 'chat',
  },
  {
    abilities: {
      vision: true,
    },
    contextWindowTokens: 32_768,
    displayName: 'Qwen2.5 VL 72B Instruct',
    family: 'qwen',
    generation: 'qwen2.5',
    id: 'qwen2.5-vl-72b-instruct',
    organization: 'Qwen',
    releasedAt: '2025-01-26',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      structuredOutput: true,
    },
    contextWindowTokens: 262_144,
    displayName: 'Qwen3 235B A22B Instruct',
    family: 'qwen',
    generation: 'qwen3',
    id: 'qwen3-235b-a22b-instruct',
    organization: 'Qwen',
    releasedAt: '2025-07-22',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      structuredOutput: true,
    },
    contextWindowTokens: 262_144,
    displayName: 'Qwen3 30B A3B Instruct',
    family: 'qwen',
    generation: 'qwen3',
    id: 'qwen3-30b-a3b-instruct',
    organization: 'Qwen',
    releasedAt: '2025-07-29',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
    },
    contextWindowTokens: 32_768,
    displayName: 'Qwen3 32B',
    family: 'qwen',
    generation: 'qwen3',
    id: 'qwen3-32b',
    organization: 'Qwen',
    releasedAt: '2025-04-28',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      structuredOutput: true,
    },
    contextWindowTokens: 262_144,
    displayName: 'Qwen3 Coder 30B A3B Instruct',
    family: 'qwen',
    generation: 'qwen3',
    id: 'qwen3-coder-30b-a3b-instruct',
    organization: 'Qwen',
    releasedAt: '2025-07-31',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
    },
    contextWindowTokens: 256_000,
    displayName: 'Qwen3 Coder Next',
    family: 'qwen',
    generation: 'qwen3',
    id: 'qwen3-coder-next',
    organization: 'Qwen',
    releasedAt: '2026-02-03',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 262_000,
    displayName: 'Qwen3.5 122B A10B',
    enabled: true,
    family: 'qwen',
    generation: 'qwen3.5',
    id: 'qwen3.5-122b-a10b',
    organization: 'Qwen',
    releasedAt: '2026-02-24',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    displayName: 'Qwen3.5 397B A17B',
    family: 'qwen',
    generation: 'qwen3.5',
    id: 'qwen3.5-397b-a17b',
    organization: 'Qwen',
    releasedAt: '2026-02-16',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 262_000,
    displayName: 'Qwen3.5 9B',
    family: 'qwen',
    generation: 'qwen3.5',
    id: 'qwen3.5-9b',
    organization: 'Qwen',
    releasedAt: '2026-03-02',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      video: true,
      vision: true,
    },
    contextWindowTokens: 262_000,
    displayName: 'Qwen 3.6 27B',
    family: 'qwen',
    generation: 'qwen3.6',
    id: 'qwen3.6-27b',
    organization: 'Qwen',
    releasedAt: '2026-04-22',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    displayName: 'Qwen 3.6 35B A3B',
    family: 'qwen',
    generation: 'qwen3.6',
    id: 'qwen3.6-35b-a3b',
    organization: 'Qwen',
    releasedAt: '2026-04-16',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      video: true,
      vision: true,
    },
    contextWindowTokens: 262_000,
    displayName: 'Qwen3.8 27B',
    family: 'qwen',
    generation: 'qwen3.8',
    id: 'qwen3.8-27b',
    organization: 'Qwen',
    releasedAt: '2026-08-05',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
    },
    contextWindowTokens: 256_000,
    displayName: 'Qwen3.8 Max',
    family: 'qwen',
    generation: 'qwen3.8',
    id: 'qwen3.8-max',
    organization: 'Qwen',
    releasedAt: '2026-08-08',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
];

export const allModels = [...meliousChatModels];

export default allModels;
