import type { AIChatModelCard } from '../types/aiModel';

export const tokenlabChatModels: AIChatModelCard[] = [
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description: "TokenLab access to GPT-5.5 through TokenLab's unified model gateway.",
    displayName: 'GPT-5.5',
    enabled: true,
    family: 'gpt',
    generation: 'gpt-5.5',
    id: 'gpt-5.5',
    maxOutput: 128_000,
    organization: 'openai',
    pricing: {
      units: [
        { name: 'textInput', rate: 1.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.15, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 9, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 1_050_000,
    description: "TokenLab access to GPT-5.5 Pro through TokenLab's unified model gateway.",
    displayName: 'GPT-5.5 Pro',
    enabled: true,
    family: 'gpt',
    generation: 'gpt-5.5',
    id: 'gpt-5.5-pro',
    maxOutput: 128_000,
    organization: 'openai',
    pricing: {
      units: [
        { name: 'textInput', rate: 30, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 180, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 400_000,
    description: "TokenLab access to GPT-5.4 through TokenLab's unified model gateway.",
    displayName: 'GPT-5.4',
    enabled: true,
    family: 'gpt',
    generation: 'gpt-5.4',
    id: 'gpt-5.4',
    maxOutput: 128_000,
    organization: 'openai',
    pricing: {
      units: [
        { name: 'textInput', rate: 0.75, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.075, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 4.5, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 400_000,
    description: "TokenLab access to GPT-5.4 Mini through TokenLab's unified model gateway.",
    displayName: 'GPT-5.4 Mini',
    enabled: true,
    family: 'gpt',
    generation: 'gpt-5.4',
    id: 'gpt-5.4-mini',
    maxOutput: 128_000,
    organization: 'openai',
    pricing: {
      units: [
        { name: 'textInput', rate: 0.225, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.0225, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 1.35, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description: "TokenLab access to Claude Fable 5 through TokenLab's unified model gateway.",
    displayName: 'Claude Fable 5',
    enabled: true,
    family: 'claude-mythos',
    generation: 'mythos-5',
    id: 'claude-fable-5',
    maxOutput: 128_000,
    organization: 'anthropic',
    pricing: {
      units: [
        { name: 'textInput', rate: 6.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.65, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 32.5, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description: "TokenLab access to Claude Opus 4.8 through TokenLab's unified model gateway.",
    displayName: 'Claude Opus 4.8',
    enabled: true,
    family: 'claude-opus',
    generation: 'claude-4.8',
    id: 'claude-opus-4-8',
    maxOutput: 128_000,
    organization: 'anthropic',
    pricing: {
      units: [
        { name: 'textInput', rate: 3.25, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.325, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 16.25, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description: "TokenLab access to Claude Sonnet 5 through TokenLab's unified model gateway.",
    displayName: 'Claude Sonnet 5',
    enabled: true,
    family: 'claude-sonnet',
    generation: 'claude-5',
    id: 'claude-sonnet-5',
    maxOutput: 128_000,
    organization: 'anthropic',
    pricing: {
      units: [
        { name: 'textInput', rate: 1.3, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.13, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 6.5, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 1_048_576,
    description: "TokenLab access to Gemini 3.5 Flash through TokenLab's unified model gateway.",
    displayName: 'Gemini 3.5 Flash',
    enabled: true,
    family: 'gemini',
    generation: 'gemini-3.5',
    id: 'gemini-3.5-flash',
    maxOutput: 65_536,
    organization: 'google',
    pricing: {
      units: [
        { name: 'textInput', rate: 0.75, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.075, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 4.5, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 1_048_576,
    description:
      "TokenLab access to Gemini 3.1 Flash Lite through TokenLab's unified model gateway.",
    displayName: 'Gemini 3.1 Flash Lite',
    enabled: true,
    family: 'gemini',
    generation: 'gemini-3.1',
    id: 'gemini-3.1-flash-lite',
    maxOutput: 65_536,
    organization: 'google',
    pricing: {
      units: [
        { name: 'textInput', rate: 0.125, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.0125, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.75, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description: "TokenLab access to Grok 4.3 through TokenLab's unified model gateway.",
    displayName: 'Grok 4.3',
    enabled: true,
    family: 'grok',
    generation: 'grok-4.3',
    id: 'grok-4.3',
    maxOutput: 131_072,
    organization: 'xai',
    pricing: {
      units: [
        { name: 'textInput', rate: 1.25, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.2, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 2.5, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 2_000_000,
    description: "TokenLab access to Grok 4 Fast through TokenLab's unified model gateway.",
    displayName: 'Grok 4 Fast',
    enabled: true,
    family: 'grok',
    generation: 'grok-4',
    id: 'grok-4-fast',
    maxOutput: 16_384,
    organization: 'xai',
    pricing: {
      units: [
        { name: 'textInput', rate: 0.2, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.05, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.5, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      structuredOutput: true,
    },
    contextWindowTokens: 1_000_000,
    description: "TokenLab access to DeepSeek v4 Pro through TokenLab's unified model gateway.",
    displayName: 'DeepSeek v4 Pro',
    enabled: true,
    family: 'deepseek',
    generation: 'deepseek-v4',
    id: 'deepseek-v4-pro',
    maxOutput: 384_000,
    organization: 'deepseek',
    pricing: {
      units: [
        { name: 'textInput', rate: 0.441_176, strategy: 'fixed', unit: 'millionTokens' },
        {
          name: 'textInput_cacheRead',
          rate: 0.003_676_47,
          strategy: 'fixed',
          unit: 'millionTokens',
        },
        { name: 'textOutput', rate: 0.882_353, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      structuredOutput: true,
    },
    contextWindowTokens: 1_000_000,
    description: "TokenLab access to DeepSeek v4 Flash through TokenLab's unified model gateway.",
    displayName: 'DeepSeek v4 Flash',
    enabled: true,
    family: 'deepseek',
    generation: 'deepseek-v4',
    id: 'deepseek-v4-flash',
    maxOutput: 384_000,
    organization: 'deepseek',
    pricing: {
      units: [
        { name: 'textInput', rate: 0.147_059, strategy: 'fixed', unit: 'millionTokens' },
        {
          name: 'textInput_cacheRead',
          rate: 0.002_941_18,
          strategy: 'fixed',
          unit: 'millionTokens',
        },
        { name: 'textOutput', rate: 0.294_118, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    contextWindowTokens: 1_000_000,
    description: "TokenLab access to GLM-5.2 through TokenLab's unified model gateway.",
    displayName: 'GLM-5.2',
    enabled: true,
    family: 'glm',
    generation: 'glm-5.2',
    id: 'glm-5.2',
    maxOutput: 128_000,
    organization: 'zhipu',
    pricing: {
      units: [
        { name: 'textInput', rate: 1.176_47, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.294_118, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 4.117_65, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    contextWindowTokens: 991_808,
    description: "TokenLab access to Qwen3.7 Max through TokenLab's unified model gateway.",
    displayName: 'Qwen3.7 Max',
    enabled: true,
    family: 'qwen',
    generation: 'qwen3.7',
    id: 'qwen3.7-max',
    maxOutput: 65_536,
    organization: 'alibaba',
    pricing: {
      units: [
        { name: 'textInput', rate: 1.764_71, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.352_941, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 5.294_12, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: { functionCall: true },
    contextWindowTokens: 1_048_576,
    description: "TokenLab access to MiniMax M3 through TokenLab's unified model gateway.",
    displayName: 'MiniMax M3',
    enabled: true,
    family: 'minimax',
    generation: 'minimax-m3',
    id: 'minimax-m3',
    maxOutput: 524_288,
    organization: 'minimax',
    pricing: {
      units: [
        { name: 'textInput', rate: 0.3, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.06, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 1.2, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 262_144,
    description: "TokenLab access to Kimi K2.7 Code through TokenLab's unified model gateway.",
    displayName: 'Kimi K2.7 Code',
    enabled: true,
    family: 'kimi',
    generation: 'kimi-k2.7',
    id: 'kimi-k2.7-code',
    maxOutput: 131_072,
    organization: 'moonshot',
    pricing: {
      units: [
        { name: 'textInput', rate: 0.95, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.19, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 4, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    contextWindowTokens: 262_144,
    description:
      "TokenLab access to Kimi K2.7 Code Highspeed through TokenLab's unified model gateway.",
    displayName: 'Kimi K2.7 Code Highspeed',
    enabled: true,
    family: 'kimi',
    generation: 'kimi-k2.7',
    id: 'kimi-k2.7-code-highspeed',
    maxOutput: 131_072,
    organization: 'moonshot',
    pricing: {
      units: [
        { name: 'textInput', rate: 1.9, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.38, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 8, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
];

export default tokenlabChatModels;
