import { createHmac, timingSafeEqual } from 'node:crypto';

import { serverDBEnv } from '@/config/db';

export const OIDC_SESSION_COOKIE_NAME = '_session';
export const OIDC_SESSION_COOKIE_NAMES = [
  OIDC_SESSION_COOKIE_NAME,
  `${OIDC_SESSION_COOKIE_NAME}.sig`,
  `${OIDC_SESSION_COOKIE_NAME}.legacy`,
  `${OIDC_SESSION_COOKIE_NAME}.legacy.sig`,
] as const;

export const getOIDCCookieKeys = () => {
  const key = serverDBEnv.KEY_VAULTS_SECRET;
  if (!key) {
    throw new Error('KEY_VAULTS_SECRET is required for OIDC Provider cookie signing');
  }
  return [key];
};

const signOIDCCookie = (name: string, value: string, key: string) =>
  createHmac('sha1', key)
    .update(`${name}=${value}`)
    .digest('base64')
    .replaceAll('/', '_')
    .replaceAll('+', '-')
    .replaceAll('=', '');

/**
 * Verifies the Keygrip signature generated by oidc-provider's `cookies` dependency.
 *
 * @see https://github.com/pillarjs/cookies/blob/0.9.1/index.js
 */
export const verifyOIDCCookieSignature = (name: string, value: string, signature: string) => {
  const actual = Buffer.from(signature);

  return getOIDCCookieKeys().some((key) => {
    const expected = Buffer.from(signOIDCCookie(name, value, key));
    return actual.length === expected.length && timingSafeEqual(actual, expected);
  });
};
